config/routes.rb
Rails.application.routes.draw do
  resources :dak_templates
  resources :followup_audits
  resources :followupaudits
  resources :sub4_fields
  resources :sub3_fields
  resources :sub2_fields
  resources :sub2_document_types
  resources :log_activities do
    get :list_login, on: :collection
    get :list_request, on: :collection
    get :report_request, on: :collection
    get :report_all, on: :collection
    get :export_request, on: :collection
    get :report_login, on: :collection
    get :export_login, on: :collection
    get :export_all, on: :collection
  end
  resources :document_classifications
  resources :internal_wr_audits
  resources :wr_doc_requests do
    collection do
      get 'edit_approve/:id' => :edit_approve, as: 'edit_approve'
      get 'download_new_request/:id' => :download_new_request, as: 'download_new_request'
      get 'do_approve_new_request/:id' => :do_approve_new_request, as: 'do_approve_new_request'
      get 'do_reject_new_request/:id' => :do_reject_new_request, as: 'do_reject_new_request'
      get 'edit_reject/:id' => :edit_reject, as: 'edit_reject'
      get 'do_approve_by_superadmin/:id' => :do_approve_by_superadmin, as: 'do_approve_by_superadmin'
      get 'download_hard_copy/:id' => :download_hard_copy, as: 'download_hard_copy'
    end
    get :new_request, on: :collection
    get :index_request, on: :collection
  end
  resources :document_requests do
    collection do
      get 'edit_approve/:id' => :edit_approve, as: 'edit_approve'
      get 'edit_reject/:id' => :edit_reject, as: 'edit_reject'
      get 'download_new_request/:id' => :download_new_request, as: 'download_new_request'
      get 'do_reject_new_request/:id' => :do_reject_new_request, as: 'do_reject_new_request'
      get 'do_approve_new_request/:id' => :do_approve_new_request, as: 'do_approve_new_request'
      get 'do_approve_by_superadmin/:id' => :do_approve_by_superadmin, as: 'do_approve_by_superadmin'
      get 'download_hard_copy/:id' => :download_hard_copy, as: 'download_hard_copy'
    end
    get :new_request, on: :collection
    get :index_request, on: :collection
  end
  resources :document_references
  resources :document_types
  resources :sub_document_types
  resources :wr_doc_types
  resources :report_distributions
  resources :reports
  resources :wr_doc_distributions do
    collection do
      get 'new_distribution/:id' => :new_distribution, as: 'new_distribution'
      get 'download_document/:id' => :download_document, as: 'download_document'
    end
  end
  resources :wr_doc_revisions
  resources :wr_docs do
    get :document_distribution, on: :collection
    get :document_approval, on: :collection
    get :document_approve_request, on: :collection
    get :document_check, on: :collection
    get :home_document, on: :collection
    get :sub_home_document, on: :collection
    get :document_request, on: :collection
    get :view_all_index, on: :collection
    get :index_request, on: :collection
    get :report, on: :collection
    get :recycle_bin, on: :collection
    get :hapus_selamanya, on: :collection
    get :hapus_forever, on: :collection
    # post :index, on: :collection
  end
  resources :wr_docs do
    collection do
      get 'view4_index/:sub4_field_id' => :view4_index, as: 'view4_index'
      get 'view3_index/:sub3_field_id' => :view3_index, as: 'view3_index'
      get 'view2_index/:sub2_field_id' => :view2_index, as: 'view2_index'
      get 'sub4_home_document/:sub3_field_id' => :sub4_home_document, as: 'sub4_home_document'
      get 'sub3_home_document/:sub2_field_id' => :sub3_home_document, as: 'sub3_home_document'
      get 'sub2_home_document/:sub_field_id' => :sub2_home_document, as: 'sub2_home_document'
      get 'soft_delete/:wr_doc_id' => :soft_delete, as: 'soft_delete'
      get 'restore/:wr_doc_id' => :restore, as: 'restore'
      get 'hapus/:wr_doc_id' => :hapus, as: 'hapus'
      get 'view_show/:wr_doc_id' => :view_show, as: 'view_show'
    end
  end
  resources :sub_fields
  resources :distributions do
    collection do
      get 'new_distribution/:id' => :new_distribution, as: 'new_distribution'
      get 'download_document/:id' => :download_document, as: 'download_document'
    end
  end
  resources :internal_audits do
    get :dashboard, on: :collection
  end
  get 'errors/error_404'
  resources :document_revisions
  resources :documents do
    get :view_index, on: :collection
    get :document_approval, on: :collection
    get :document_approve_request, on: :collection
    get :document_check, on: :collection
    get :view_all_index, on: :collection
    get :index_request, on: :collection
    get :document_tracking, on: :collection
    get :document_distribution, on: :collection
    get :document_request, on: :collection
    get :home_qms, on: :collection
    get :home, on: :collection
    get :hapus_forever, on: :collection
    get :report, on: :collection
    get :recycle_bin, on: :collection
    # post :view_all_index, on: :collection
  end
  resources :documents do
    collection do
      get 'report_dak/:document_type_id' => :report_dak, as: 'report_dak'
      get 'report_corporate/:document_type_id' => :report_corporate, as: 'report_corporate'
      get 'sub2_home_qms/:sub_document_type_id' => :sub2_home_qms, as: 'sub2_home_qms'
      get 'view2_base_type/:sub2_document_type_id' => :view2_base_type, as: 'view2_base_type'
      get 'soft_delete/:document_id' => :soft_delete, as: 'soft_delete'
      get 'restore/:document_id' => :restore, as: 'restore'
      get 'hapus/:document_id' => :hapus, as: 'hapus'
      get 'view_show/:document_id' => :view_show, as: 'view_show'
    end
  end
  resources :fields
  resources :permissions
  resources :roles
  controller :sessions do
    get 'switch_role' => :switch_role
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  devise_for :users, controllers: {sessions: "sessions"}
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :members do
    get :ldap, on: :collection
    get :new_ldap, on: :collection
    get :export_user, on: :collection
  end
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'dashboard#analytics'
  root 'documents#home'
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',

app/models/document.rb
class Document < ApplicationRecord
  acts_as_paranoid
  has_many :document_revision
  has_many :document_distribution
  belongs_to :document_type
  belongs_to :sub_document_type
  belongs_to :document_reference
  belongs_to :document_classification, optional: true
  belongs_to :sub2_document_type, optional: true
  has_many :document_request
  before_create :setStatus

  def setStatus
    if self.status == "Request"
      self.status = self.status
      self.reason = self.reason
    else
      self.status = "Open"
    end
  end

  def self.view_base_type(document_title,document_code,document_date,sub_field,sub_type,sub_document_type_id)
    if document_title.present? and !document_code.present? and !document_date.present?
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where('documents.sub_document_type_id = ? and documents.document_title LIKE ? or documents.sub_document_type_id = ? and documents.document_title LIKE ?', sub_type, "%#{document_title.titleize}%", sub_type, "%#{document_title.downcase}%").select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    elsif document_code.present? and !document_title.present? and !document_date.present?
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where('documents.sub_document_type_id = ? and documents.document_code LIKE ?', sub_type, "%#{document_code}%").select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    elsif document_date.present? and !document_title.present? and !document_code.present?
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where('documents.sub_document_type_id = ? and documents.document_date = ?', sub_type, "#{document_date}").select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    elsif !sub_field.nil?
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where(sub_document_type_id: sub_type).select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    else
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where(sub_document_type_id: sub_document_type_id).select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    end
  end

  def self.view2_base_type(document_title,document_code,document_date,sub_field,sub_type,sub2_document_type_id)
    if document_title.present? and !document_code.present? and !document_date.present?
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where('documents.sub2_document_type_id = ? and documents.document_title LIKE ? or documents.sub_document_type_id = ? and documents.document_title LIKE ?', sub_type, "%#{document_title.titleize}%", sub_type, "%#{document_title.downcase}%").select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    elsif document_code.present? and !document_title.present? and !document_date.present?
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where('documents.sub2_document_type_id = ? and documents.document_code LIKE ?', sub_type, "%#{document_code}%").select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    elsif document_date.present? and !document_title.present? and !document_code.present?
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where('documents.sub2_document_type_id = ? and documents.document_date = ?', sub_type, "#{document_date}").select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    elsif !sub_field.nil?
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where(sub2_document_type_id: sub_type).select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    else
      left_outer_joins(:document_type, :sub_document_type, :document_reference, :document_classification, :sub2_document_type).where(sub2_document_type_id: sub2_document_type_id).select('*').order('documents.document_date DESC')
      # expires_in 5.minutes, public: true
    end
  end
end

app/models/document_type.rb
class DocumentType < ApplicationRecord
  has_many :sub_document_type
  has_many :document
  validates :type_name, uniqueness: true
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_show.html.erb
<!-- MAIN CONTENT -->
<div id="error_explanation" class="bg-danger text-danger"></div>
<div class="modal-body">
  <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-1" data-widget-editbutton="false">
    <div class="widget-body">
      <dl class="dl-horizontal">
        <div id="myTabContent" class="tab-content">
          <div class="ibox float-e-margins">
            <div class="ibox-title">
              <div class="ibox-content" style="display: block;">
                <table class="table table-bordered">
                  <tr>
                    <td colspan="2" align="center"><strong>DETAIL</strong></td>
                  </tr>
                  <tr>
                    <td><strong>Nomor Dokumen:</strong></td>
                    <!--                      <td class="gen_number"><-->
                    <!--                        <b><%#=@number%></b> <span class="label label-warning" title="Silahkan ganti status terlebih dahulu menjadi Request Procurement"><i class="fa fa-info"></i></span>-->
                    <!--                      </td>-->
                    <td><b><%= @document.first.document_code.to_s %></b></td>
                  </tr>
                  <tr>
                    <td><strong>Judul Dokumen:</strong></td>
                    <td><%= @document.first.document_title.to_s %></td>
                  </tr>

                  <tr>
                    <td><strong>Jenis Dokumen:</strong></td>
                    <td><%= @document.first.type_name.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Sub Jenis Dokumen:</strong></td>
                    <td><%= @document.first.sub_type_name.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Klasifikasi Dokumen:</strong></td>
                    <td><%= @document.first.classification_name.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Tipe Dokumen:</strong></td>
                    <td><%= @document.first.reference_name.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Sifat Dokumen:</strong></td>
                    <td><%= @document.first.sifat.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Issued By:</strong></td>
                    <td><%= @document.first.issued_by.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Tanggal Berlaku:</strong></td>
                    <% if @document.first.document_date.to_s.present? %>
                      <td><%= @document.first.document_date.strftime('%d %b %Y') %></td>
                    <% else %>
                      <td>-</td>
                    <% end %>
                  </tr>
                  <tr>
                    <td><strong>Revisi:</strong></td>
                    <td><%= @document.first.revision.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Penanggung Jawab:</strong></td>
                    <td><%= @document.first.penanggung_jawab.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Lokasi Simpan:</strong></td>
                    <td><%= @document.first.save_location.to_s %></td>
                  </tr>
                  <tr>
                    <td><strong>Lama Simpan:</strong></td>
                    <% if @document.first.save_date.to_s.present? %>
                      <td><%= distance_of_time_in_words(Time.now, @document.first.save_date.to_s, true, :only => [:years, :months, :weeks, :days]) %></td>
                    <% else %>
                      <td>-</td>
                    <% end %>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </dl>
    </div>
  </div>
</div>

app/views/documents/edit.html.erb
<!-- MAIN CONTENT -->
<div id="content">
  <% content_for :ribbon do %>
    <!-- RIBBON -->
    <div id="ribbon">

    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>

      <!-- breadcrumb -->
      <ol class="breadcrumb">
        <!--      <li><a href="<%#= home_documents_path %>">HOME</a></li><li><a href="<%#= home_qms_documents_path %>">QM System</a></li><li>Control Management</li><li><a href="<%#= documents_url %>">Manage Document</a></li><li>Edit Document</li>-->
        <li><a href="<%= home_documents_path %>">HOME</a></li><li><a href="<%= home_qms_documents_path %>">QM System</a></li><li><a href="#" onclick="return goBack()">Previous</a></li><li>Edit Document</li>
        <script type="text/javascript" charset="utf-8">
            function goBack() {
                window.history.back();
            }
        </script>
      </ol>
      <!-- end breadcrumb -->

      <!-- You can also add more buttons to the
      ribbon for further usability

      Example below:

      <span class="ribbon-button-alignment pull-right">
      <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
      <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
      <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
      </span> -->

    </div>
    <!-- END RIBBON -->
  <% end %>
  <div class="page-header">
    <%# <%= link_to documents_path, class: 'btn btn-default' do %>
    <!-- <span class="glyphicon glyphicon-list-alt"></span> -->
    <%# Back %>
    <%# <% end %>
    <%# <%= link_to @document, class: 'btn btn-primary' do %>
    <!-- <span class="glyphicon glyphicon-info-sign"></span> -->
    <!-- Show -->
    <%# <% end %>
    <h1>Editing document</h1>
    <%= render "layouts/logo_header" %>
  </div>

  <%= render 'form_custome' %>
</div>

app/views/documents/new.html.erb
<!-- MAIN CONTENT -->
<div id="content">
  <% content_for :ribbon do %>
    <!-- RIBBON -->
    <div id="ribbon">

    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>

      <!-- breadcrumb -->
      <ol class="breadcrumb">
        <li><a href="<%= home_documents_path %>">HOME</a></li>
        <li><a href="<%= home_qms_documents_path %>">QM System</a></li>
        <li>Document Control</li>
        <li>New Document</li>
      </ol>
      <!-- end breadcrumb -->

      <!-- You can also add more buttons to the
      ribbon for further usability

      Example below:

      <span class="ribbon-button-alignment pull-right">
      <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
      <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
      <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
      </span> -->

    </div>
    <!-- END RIBBON -->
  <% end %>
  <div class="page-header">
    <%# <%= link_to documents_path, class: 'btn btn-default' do %>
    <!-- <span class="glyphicon glyphicon-list-alt"></span> -->
    <!-- Back -->
    <%# <% end %>
    <h1>New document</h1>
    <%= render "layouts/logo_header" %>
  </div>

  <%= render 'form_custome' %>
</div>

app/views/documents/sub2_home_qms.html.erb
<!-- MAIN CONTENT -->
<div id="content">
  <% content_for :ribbon do %>
    <!-- RIBBON -->
    <div id="ribbon">

    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>

      <!-- breadcrumb -->
      <ol class="breadcrumb">
        <span class="project-selector dropdown-toggle" data-toggle="dropdown" style="color: #bababa;"><%= _('...') %>
          <i class="fa fa-angle-down"></i></span>
        <% @sub = Sub2DocumentType.joins(:sub_document_type).where(sub_document_type_id: params[:sub_document_type_id]).select('*') %>
        <% @document = DocumentType.find_by(document_type_id: @sub.first.document_type_id.to_s) %>
        <ul class="dropdown-menu">
          <li><a href="<%= root_path %>" style="text-decoration:none;">HOME</a></li>
          <li><a href="<%= home_qms_documents_path %>" style="text-decoration:none;">Quality Documents</a></li>
          <li>
            <a href="<%= sub_type_document_path(@document.document_type_id) %>" style="text-decoration:none;"><%= "#{@document.type_name}" %></a>
          </li>
        </ul>
        <li><%= "#{@sub.first.sub_type_name.to_s.gsub('/', 'atau').truncate(35, sparator:"...")}" %></li>
      </ol>
      <!-- end breadcrumb -->

      <!-- You can also add more buttons to the
      ribbon for further usability

      Example below:

      <span class="ribbon-button-alignment pull-right">
      <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
      <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
      <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
      </span> -->

    </div>
    <!-- END RIBBON -->
  <% end %>
  <div class="page-header">
    <h1>List Items - <%= @sub.first.sub_type_name.to_s.gsub('/', 'atau') %></h1>
    <%= render "layouts/logo_header" %>
  </div>

  <%= render 'layouts/css_cards' %>

  <dl class="dl-horizontal">
    <div class="row animated fadeInDown">
      <hr style="border-color: black;">
      <%
        @field.each do |f|
          cache f do
  %>
        <div class="col-lg-2 col-md-2 col-xs-6 col-sm-3" id="card">
          <!--<span class="label label-success pull-right">Monthly</span>-->
          <div class="card">
            <a href="<%= view2_base_type_documents_path(f.sub2_document_type_id) %>" style="text-decoration:none; color:black;" title="<%= f.sub2_type_name %>">
              <h3 class="title"><%= f.sub2_type_name %></h3>
              <div class="bar">
                <div class="emptybar"></div>
                <div class="filledbar"></div>
                <% @WrDoc = Document.where('sub2_document_type_id = ?', f.sub2_document_type_id).select('*') %>
                <h2 class="no-margins text-navy" style="color:#42f4a1;"><%= @WrDoc.count %></h2>
              </div>
            </a>
          </div>
          <br>
        </div>
      <% end end %>
    </div>
  </dl>
  <%#= render 'layouts/pagination_cards' %>
  <%#= will_paginate @field, renderer: @custom_paginate_renderer %>
</div>