config/routes.rb
Rails.application.routes.draw do
  resources :dak_templates
  resources :followup_audits
  resources :followupaudits
  resources :sub4_fields
  resources :sub3_fields
  resources :sub2_fields
  resources :sub2_document_types
  resources :log_activities do
    get :list_login, on: :collection
    get :list_request, on: :collection
    get :report_request, on: :collection
    get :report_all, on: :collection
    get :export_request, on: :collection
    get :report_login, on: :collection
    get :export_login, on: :collection
    get :export_all, on: :collection
  end
  resources :document_classifications
  resources :internal_wr_audits
  resources :wr_doc_requests do
    collection do
      get 'edit_approve/:id' => :edit_approve, as: 'edit_approve'
      get 'download_new_request/:id' => :download_new_request, as: 'download_new_request'
      get 'do_approve_new_request/:id' => :do_approve_new_request, as: 'do_approve_new_request'
      get 'do_reject_new_request/:id' => :do_reject_new_request, as: 'do_reject_new_request'
      get 'edit_reject/:id' => :edit_reject, as: 'edit_reject'
      get 'do_approve_by_superadmin/:id' => :do_approve_by_superadmin, as: 'do_approve_by_superadmin'
      get 'download_hard_copy/:id' => :download_hard_copy, as: 'download_hard_copy'
    end
    get :new_request, on: :collection
    get :index_request, on: :collection
  end
  resources :document_requests do
    collection do
      get 'edit_approve/:id' => :edit_approve, as: 'edit_approve'
      get 'edit_reject/:id' => :edit_reject, as: 'edit_reject'
      get 'download_new_request/:id' => :download_new_request, as: 'download_new_request'
      get 'do_reject_new_request/:id' => :do_reject_new_request, as: 'do_reject_new_request'
      get 'do_approve_new_request/:id' => :do_approve_new_request, as: 'do_approve_new_request'
      get 'do_approve_by_superadmin/:id' => :do_approve_by_superadmin, as: 'do_approve_by_superadmin'
      get 'download_hard_copy/:id' => :download_hard_copy, as: 'download_hard_copy'
    end
    get :new_request, on: :collection
    get :index_request, on: :collection
  end
  resources :document_references
  resources :document_types
  resources :sub_document_types
  resources :wr_doc_types
  resources :report_distributions
  resources :reports
  resources :wr_doc_distributions do
    collection do
      get 'new_distribution/:id' => :new_distribution, as: 'new_distribution'
      get 'download_document/:id' => :download_document, as: 'download_document'
    end
  end
  resources :wr_doc_revisions
  resources :wr_docs do
    get :document_distribution, on: :collection
    get :document_approval, on: :collection
    get :document_approve_request, on: :collection
    get :document_check, on: :collection
    get :home_document, on: :collection
    get :sub_home_document, on: :collection
    get :document_request, on: :collection
    get :view_all_index, on: :collection
    get :index_request, on: :collection
    get :report, on: :collection
    get :recycle_bin, on: :collection
    get :hapus_selamanya, on: :collection
    get :hapus_forever, on: :collection
    # post :index, on: :collection
  end
  resources :wr_docs do
    collection do
      get 'view4_index/:sub4_field_id' => :view4_index, as: 'view4_index'
      get 'view3_index/:sub3_field_id' => :view3_index, as: 'view3_index'
      get 'view2_index/:sub2_field_id' => :view2_index, as: 'view2_index'
      get 'sub4_home_document/:sub3_field_id' => :sub4_home_document, as: 'sub4_home_document'
      get 'sub3_home_document/:sub2_field_id' => :sub3_home_document, as: 'sub3_home_document'
      get 'sub2_home_document/:sub_field_id' => :sub2_home_document, as: 'sub2_home_document'
      get 'soft_delete/:wr_doc_id' => :soft_delete, as: 'soft_delete'
      get 'restore/:wr_doc_id' => :restore, as: 'restore'
      get 'hapus/:wr_doc_id' => :hapus, as: 'hapus'
      get 'view_show/:wr_doc_id' => :view_show, as: 'view_show'
    end
  end
  resources :sub_fields
  resources :distributions do
    collection do
      get 'new_distribution/:id' => :new_distribution, as: 'new_distribution'
      get 'download_document/:id' => :download_document, as: 'download_document'
    end
  end
  resources :internal_audits do
    get :dashboard, on: :collection
  end
  get 'errors/error_404'
  resources :document_revisions
  resources :documents do
    get :view_index, on: :collection
    get :document_approval, on: :collection
    get :document_approve_request, on: :collection
    get :document_check, on: :collection
    get :view_all_index, on: :collection
    get :index_request, on: :collection
    get :document_tracking, on: :collection
    get :document_distribution, on: :collection
    get :document_request, on: :collection
    get :home_qms, on: :collection
    get :home, on: :collection
    get :hapus_forever, on: :collection
    get :report, on: :collection
    get :recycle_bin, on: :collection
    # post :view_all_index, on: :collection
  end
  resources :documents do
    collection do
      get 'report_dak/:document_type_id' => :report_dak, as: 'report_dak'
      get 'report_corporate/:document_type_id' => :report_corporate, as: 'report_corporate'
      get 'sub2_home_qms/:sub_document_type_id' => :sub2_home_qms, as: 'sub2_home_qms'
      get 'view2_base_type/:sub2_document_type_id' => :view2_base_type, as: 'view2_base_type'
      get 'soft_delete/:document_id' => :soft_delete, as: 'soft_delete'
      get 'restore/:document_id' => :restore, as: 'restore'
      get 'hapus/:document_id' => :hapus, as: 'hapus'
      get 'view_show/:document_id' => :view_show, as: 'view_show'
    end
  end
  resources :fields
  resources :permissions
  resources :roles
  controller :sessions do
    get 'switch_role' => :switch_role
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  devise_for :users, controllers: {sessions: "sessions"}
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :members do
    get :ldap, on: :collection
    get :new_ldap, on: :collection
    get :export_user, on: :collection
  end
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'dashboard#analytics'
  root 'documents#home'
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',

app/models/field.rb
class Field < ApplicationRecord
has_many :sub_field
has_many :wr_doc
validates :description_field, uniqueness: true
end

app/controllers/api/v1/fields_controller.rb
module Api
  module V1
    class FieldsController < ApplicationController
      # skip_before_action :logged_in_user
      before_action :has_valid_api_key!
      def index
        fields = Field.order('created_at DESC');
        render json: {status: 'SUCCESSFULLY', message:'loaded fields', data:fields}, status: :ok
      end
      def show
        fields = Field.find(params[:id])
        render json: {status: 'SUCCESSFULLY', message:'loaded fields', data:fields}, status: :ok
      end
      def create
        fields = Field.new(field_params)
        if fields.save
          render json: {status: 'SUCCESSFULLY', message:'saved fields', data:fields}, status: :ok
        else
          render json: {status: 'Error', message:'Fields is not saved', data:fields.errors}, status: :unprocessable_entity
        end
      end
      def update
        fields = Field.find(params[:id])
        if fields.update_attributes(field_params)
          render json: {status: 'SUCCESSFULLY', message:'Field is update', data:fields}, status: :ok
        else
          render json: {status: 'Error', message:'Field is not update', data:fields.errors}, status: :unprocessable_entity
        end
      end
      def destroy
        fields = Field.find(params[:id])
        fields.destroy
        render json: {status: 'SUCCESSFULLY', message:'Some field has been Deleted', data:fields}, status: :ok
      end
      private
      def field_params
        params.require(:field).permit(:description_field)
      end
      def has_valid_api_key?
        request.headers['X-Api-Key'] == 'Pg4550Lut1oN!'
      end
      def has_valid_api_key!
        return head :forbidden unless has_valid_api_key?
      end
    end
  end
end

app/controllers/fields_controller.rb
#Developer : Mohamad Rinaldi Fauzi
#DB table : fields
#Module : WR (Work References)
#Sifat Tabel : Master
#Ket : Data master field
class FieldsController < ApplicationController
  before_action :logged_in_user
  #before_action :token_exist?
  protect_from_forgery :except => [:update, :destroy, :create]
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :json
  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)
    @akses = []
    @akses = params[:field][:akses]
    @field.akses = @akses

    respond_to do |format|
      if @field.save
        # format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.html { redirect_to fields_url, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        @setAkses = Field.find(params[:id])
        @akses = []
        @akses = params[:field][:akses]
        @setAkses.update(akses: @akses)

        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Wr doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:description_field, :akses)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/edit.html.erb
<!-- MAIN CONTENT -->
<div id="content">
  <% content_for :ribbon do %>
    <!-- RIBBON -->
    <div id="ribbon">

    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>

      <!-- breadcrumb -->
      <ol class="breadcrumb">
        <li><a href="<%= home_documents_path %>" style="text-docoration: none;">HOME</a></li>
        <li><a href="<%= fields_url %>" style="text-docoration: none;">Fields</a></li>
        <li>Edit</li>

      </ol>
      <!-- end breadcrumb -->

      <!-- You can also add more buttons to the
      ribbon for further usability

      Example below:

      <span class="ribbon-button-alignment pull-right">
      <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
      <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
      <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
      </span> -->

    </div>
    <!-- END RIBBON -->
  <% end %>
  <div class="page-header animated fadeInRight">
    <%#= link_to wr_docs_path, class: 'btn btn-default' do %>
    <!--    <span class="glyphicon glyphicon-list-alt"></span>-->
    <!--    Back-->
    <%# end %>
    <%#= link_to @wr_doc, class: 'btn btn-primary' do %>
    <!--    <span class="glyphicon glyphicon-info-sign"></span>-->
    <!--    Show-->
    <%# end %>
    <h1>Editing Field</h1>
    <%= render "layouts/logo_header" %>
  </div>

  <%= render 'form' %>
</div>

app/views/fields/index.html.erb
<!-- MAIN CONTENT -->
<div id="content">
  <% content_for :ribbon do %>
    <!-- RIBBON -->
    <div id="ribbon">

    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>

      <!-- breadcrumb -->
      <ol class="breadcrumb">
        <li><a href="<%= home_documents_path %>" style="text-docoration: none;">HOME</a></li>
        <li>Fields</li>
      </ol>
      <!-- end breadcrumb -->

      <!-- You can also add more buttons to the
      ribbon for further usability

      Example below:

      <span class="ribbon-button-alignment pull-right">
      <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
      <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
      <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
      </span> -->

    </div>
    <!-- END RIBBON -->
  <% end %>
  <div class="page-header">
    <% unless current_user.is? 19 %>
      <%= link_to new_field_path, class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-plus"></span>
        New Fields
      <% end %>
    <% end %>
    <h1>Listing Fields</h1>
    <%= render "layouts/logo_header" %>
  </div>

  <div class="jarviswidget jarviswidget-color-blueDark animated fadeInRight" id="wid-id-1" data-widget-editbutton="false">
    <!-- widget options:
    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

    data-widget-colorbutton="false"
    data-widget-editbutton="false"
    data-widget-togglebutton="false"
    data-widget-deletebutton="false"
    data-widget-fullscreenbutton="false"
    data-widget-custombutton="false"
    data-widget-collapsed="true"
    data-widget-sortable="false"

    -->
    <header>
      <span class="widget-icon"> <i class="fa fa-table"></i> </span>
      <h2>Fields </h2>

    </header>

    <!-- widget div-->
    <div>

      <!-- widget edit box -->
      <div class="jarviswidget-editbox">
        <!-- This area used as dropdown edit box -->

      </div>
      <!-- end widget edit box -->

      <!-- widget content -->
      <div class="widget-body no-padding">

        <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">

          <thead>
          <tr>
            <th class="hasinput" style="width:17%">
              <input type="text" class="form-control" placeholder="Description"/>
            </th>

          </tr>
          <tr>
            <th data-class="expand">Description</th>

            <th data-hide="phone,tablet"></th>
            <th data-hide="phone,tablet"></th>
            <th data-hide="phone,tablet"></th>
          </tr>
          </thead>

          <tbody>
          <%= content_tag_for(:tr, @fields) do |field| %>
            <td><%= field.description_field %></td>
            <td><%= link_to 'Show', field %></td>
            <% if current_user.is? 19 %>
              <% if field.akses.present? %>
                <% @getId = Member.find_by_username(current_user.username) %>
                <% @checking = Field.where('akses IN (?)', @getId.member_id).select('*') %>
                <% unless @checking.nil? %>
                  <td><%= link_to 'Edit', edit_field_path(field) %></td>
                  <td><%= link_to 'Delete', field, method: :delete, data: {confirm: 'Are you sure?'} %></td>
                <% else %>
                  <td></td>
                  <td></td>
                <% end %>
              <% else %>
                  <td></td>
                  <td></td>
              <% end %>
            <% else %>
              <td><%= link_to 'Edit', edit_field_path(field) %></td>
              <td><%= link_to 'Delete', field, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <% end %>
          <% end %>
          </tbody>

        </table>

      </div>
      <!-- end widget content -->

    </div>
    <!-- end widget div -->

  </div>
  <% content_for :scripts do %>

    <script type="text/javascript">

        // DO NOT REMOVE : GLOBAL FUNCTIONS!

        $(document).ready(function () {

            pageSetUp();

            /* // DOM Position key index //

             l - Length changing (dropdown)
             f - Filtering input (search)
             t - The Table! (datatable)
             i - Information (records)
             p - Pagination (paging)
             r - pRocessing
             < and > - div elements
             <"#id" and > - div with an id
             <"class" and > - div with a class
             <"#id.class" and > - div with an id and class

             Also see: http://legacy.datatables.net/usage/features
             */

            /* BASIC ;*/
            var responsiveHelper_dt_basic = undefined;
            var responsiveHelper_datatable_fixed_column = undefined;
            var responsiveHelper_datatable_col_reorder = undefined;
            var responsiveHelper_datatable_tabletools = undefined;

            var breakpointDefinition = {
                tablet: 1024,
                phone: 480
            };

            $('#dt_basic').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth": true,
                "oLanguage": {
                    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                },
                "preDrawCallback": function () {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
                    }
                },
                "rowCallback": function (nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback": function (oSettings) {
                    responsiveHelper_dt_basic.respond();
                }
            });

            /* END BASIC */

            /* COLUMN FILTER  */
            var otable = $('#datatable_fixed_column').DataTable({
                //"bFilter": false,
                //"bInfo": false,
                //"bLengthChange": false
                //"bAutoWidth": false,
                //"bPaginate": false,
                //"bStateSave": true // saves sort state using localStorage
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth": true,
                "oLanguage": {
                    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                },
                "preDrawCallback": function () {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_datatable_fixed_column) {
                        responsiveHelper_datatable_fixed_column = new ResponsiveDatatablesHelper($('#datatable_fixed_column'), breakpointDefinition);
                    }
                },
                "rowCallback": function (nRow) {
                    responsiveHelper_datatable_fixed_column.createExpandIcon(nRow);
                },
                "drawCallback": function (oSettings) {
                    responsiveHelper_datatable_fixed_column.respond();
                }

            });

            // Apply the filter
            $("#datatable_fixed_column thead th input[type=text]").on('keyup change', function () {

                otable
                    .column($(this).parent().index() + ':visible')
                    .search(this.value)
                    .draw();

            });
            /* END COLUMN FILTER */

            /* COLUMN SHOW - HIDE */
            $('#datatable_col_reorder').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                "autoWidth": true,
                "oLanguage": {
                    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                },
                "preDrawCallback": function () {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_datatable_col_reorder) {
                        responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
                    }
                },
                "rowCallback": function (nRow) {
                    responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
                },
                "drawCallback": function (oSettings) {
                    responsiveHelper_datatable_col_reorder.respond();
                }
            });

            /* END COLUMN SHOW - HIDE */

            /* TABLETOOLS */
            $('#datatable_tabletools').dataTable({

                // Tabletools options:
                //   https://datatables.net/extensions/tabletools/button_options
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                "oLanguage": {
                    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                },
                "oTableTools": {
                    "aButtons": [
                        "copy",
                        "csv",
                        "xls",
                        {
                            "sExtends": "pdf",
                            "sTitle": "SmartAdmin_PDF",
                            "sPdfMessage": "SmartAdmin PDF Export",
                            "sPdfSize": "letter"
                        },
                        {
                            "sExtends": "print",
                            "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
                        }
                    ],
                    "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
                },
                "autoWidth": true,
                "preDrawCallback": function () {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_datatable_tabletools) {
                        responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
                    }
                },
                "rowCallback": function (nRow) {
                    responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
                },
                "drawCallback": function (oSettings) {
                    responsiveHelper_datatable_tabletools.respond();
                }
            });

            /* END TABLETOOLS */

        })

    </script>
  <% end %>
</div>

app/views/fields/show.html.erb
<div class="page-header">
  <%= link_to fields_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_field_path(@field), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show field</h1>
  <%= render "layouts/logo_header" %>
</div>

<dl class="dl-horizontal">
  <dt>Description:</dt>
  <dd><%= @field.description_field %></dd>

</dl>